-- MySQL Script generated by MySQL Workbench
-- Sat Apr  7 10:22:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema graficasys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema graficasys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `graficasys` DEFAULT CHARACTER SET utf8 ;
USE `graficasys` ;

-- -----------------------------------------------------
-- Table `graficasys`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graficasys`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graficasys`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graficasys`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `descricao` VARCHAR(255) NULL,
  `preco` FLOAT NULL,
  `altura` FLOAT NULL,
  `comprimento` FLOAT NULL,
  `largura` FLOAT NULL,
  `peso` FLOAT NULL,
  `estado` TINYINT NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idproduto`, `categoria_idcategoria`),
  INDEX `fk_produto_categoria1_idx` (`categoria_idcategoria` ASC),
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `graficasys`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graficasys`.`item_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graficasys`.`item_produto` (
  `iditemproduto` INT NOT NULL AUTO_INCREMENT,
  `qtd` INT NULL,
  `obs` VARCHAR(255) NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`iditemproduto`, `produto_idproduto`),
  INDEX `fk_item_produto_produto1_idx` (`produto_idproduto` ASC),
  CONSTRAINT `fk_item_produto_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `graficasys`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graficasys`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graficasys`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(255) NULL,
  `numero` VARCHAR(10) NULL,
  `bairro` VARCHAR(45) NULL,
  `municipio` VARCHAR(45) NULL,
  `uf` VARCHAR(2) NULL,
  `pais` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `referencia` VARCHAR(45) NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graficasys`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graficasys`.`fornecedor` (
  `idfornecedor` INT NOT NULL AUTO_INCREMENT,
  `razaosocial` VARCHAR(255) NULL,
  `cnpj` VARCHAR(45) NULL,
  `nome` VARCHAR(255) NULL,
  `sexo` ENUM('M', 'F') NULL,
  `dtnascimento` DATE NULL,
  `numcelular` VARCHAR(11) NULL,
  `numfixo` VARCHAR(10) NULL,
  `criadoem` TIMESTAMP NULL,
  `estado` TINYINT NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`idfornecedor`, `endereco_idendereco`),
  INDEX `fk_fornecedor_endereco1_idx` (`endereco_idendereco` ASC),
  CONSTRAINT `fk_fornecedor_endereco1`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `graficasys`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graficasys`.`entrada_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graficasys`.`entrada_produto` (
  `identradaproduto` INT NOT NULL AUTO_INCREMENT,
  `qtd` INT NULL,
  `dtentrada` DATE NULL,
  `item_produto_iditemproduto` INT NOT NULL,
  `fornecedor_idfornecedor` INT NOT NULL,
  PRIMARY KEY (`identradaproduto`, `item_produto_iditemproduto`, `fornecedor_idfornecedor`),
  INDEX `fk_entrada_produto_item_produto1_idx` (`item_produto_iditemproduto` ASC),
  INDEX `fk_entrada_produto_fornecedor1_idx` (`fornecedor_idfornecedor` ASC),
  CONSTRAINT `fk_entrada_produto_item_produto1`
    FOREIGN KEY (`item_produto_iditemproduto`)
    REFERENCES `graficasys`.`item_produto` (`iditemproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrada_produto_fornecedor1`
    FOREIGN KEY (`fornecedor_idfornecedor`)
    REFERENCES `graficasys`.`fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graficasys`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graficasys`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `nome` VARCHAR(255) NULL,
  `sexo` ENUM('M', 'F') NULL,
  `dtnascimento` DATE NULL,
  `numcelular` VARCHAR(11) NULL,
  `numfixo` VARCHAR(10) NULL,
  `criadoem` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` TINYINT NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`idcliente`, `endereco_idendereco`),
  INDEX `fk_cliente_endereco_idx` (`endereco_idendereco` ASC),
  CONSTRAINT `fk_cliente_endereco`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `graficasys`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graficasys`.`artefinalista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graficasys`.`artefinalista` (
  `idartefinalista` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `nome` VARCHAR(255) NULL,
  `sexo` ENUM('M', 'F') NULL,
  `dtnascimento` DATE NULL,
  `numcelular` VARCHAR(11) NULL,
  `numfixo` VARCHAR(10) NULL,
  `criadoem` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` TINYINT NULL,
  `endereco_idendereco` INT NOT NULL,
  `salario` FLOAT NULL,
  `dtadmissao` DATE NULL,
  PRIMARY KEY (`idartefinalista`, `endereco_idendereco`),
  INDEX `fk_cliente_endereco_idx` (`endereco_idendereco` ASC),
  CONSTRAINT `fk_cliente_endereco0`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `graficasys`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graficasys`.`gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graficasys`.`gerente` (
  `idgerente` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `nome` VARCHAR(255) NULL,
  `sexo` ENUM('M', 'F') NULL,
  `dtnascimento` DATE NULL,
  `numcelular` VARCHAR(11) NULL,
  `numfixo` VARCHAR(10) NULL,
  `criadoem` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` TINYINT NULL,
  `endereco_idendereco` INT NOT NULL,
  `salario` FLOAT NULL,
  `dtadmissao` DATE NULL,
  PRIMARY KEY (`idgerente`, `endereco_idendereco`),
  INDEX `fk_cliente_endereco_idx` (`endereco_idendereco` ASC),
  CONSTRAINT `fk_cliente_endereco00`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `graficasys`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graficasys`.`atendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graficasys`.`atendente` (
  `idatendente` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `nome` VARCHAR(255) NULL,
  `sexo` ENUM('M', 'F') NULL,
  `dtnascimento` DATE NULL,
  `numcelular` VARCHAR(11) NULL,
  `numfixo` VARCHAR(10) NULL,
  `criadoem` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` TINYINT NULL,
  `endereco_idendereco` INT NOT NULL,
  `salario` FLOAT NULL,
  `dtadmissao` DATE NULL,
  PRIMARY KEY (`idatendente`, `endereco_idendereco`),
  INDEX `fk_cliente_endereco_idx` (`endereco_idendereco` ASC),
  CONSTRAINT `fk_cliente_endereco01`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `graficasys`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graficasys`.`saida_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graficasys`.`saida_produto` (
  `idsaida_produto` INT NOT NULL AUTO_INCREMENT,
  `dtsaida` DATE NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`idsaida_produto`, `produto_idproduto`),
  INDEX `fk_saida_produto_produto1_idx` (`produto_idproduto` ASC),
  CONSTRAINT `fk_saida_produto_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `graficasys`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graficasys`.`item_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graficasys`.`item_pedido` (
  `iditempedido` INT NOT NULL AUTO_INCREMENT,
  `qtd` INT NULL,
  `saida_produto_idsaida_produto` INT NOT NULL,
  PRIMARY KEY (`iditempedido`, `saida_produto_idsaida_produto`),
  INDEX `fk_itempedido_saida_produto1_idx` (`saida_produto_idsaida_produto` ASC),
  CONSTRAINT `fk_itempedido_saida_produto1`
    FOREIGN KEY (`saida_produto_idsaida_produto`)
    REFERENCES `graficasys`.`saida_produto` (`idsaida_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graficasys`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graficasys`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL,
  `dtabertura` DATE NULL,
  `dtfechamento` DATE NULL,
  `valor` FLOAT NULL,
  `obs` VARCHAR(255) NULL,
  `estado` TINYINT NULL,
  `alterado` DATE NULL,
  `criadoem` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `itempedido_iditempedido` INT NOT NULL,
  PRIMARY KEY (`idpedido`, `itempedido_iditempedido`),
  INDEX `fk_pedido_itempedido1_idx` (`itempedido_iditempedido` ASC),
  CONSTRAINT `fk_pedido_itempedido1`
    FOREIGN KEY (`itempedido_iditempedido`)
    REFERENCES `graficasys`.`item_pedido` (`iditempedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
